Repository SOPT-all/36-COLLABORATION-iOS-HOLIX, pull requests merged in 2025-05, with the labels that each got.

#7 [settings] 컬러 세팅
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/Global/Extension/UIColor+.swift
Labels: Add

#12 [feat] 하단 Tabber 구현 및 상단 Tabber 컴포넌트화
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/App/AppDelegate.swift
  HOLIX_iOS/HOLIX_iOS/App/SceneDelegate.swift
  HOLIX_iOS/HOLIX_iOS/Global/Component/TopTabBar/TopTabBarView.swift
  HOLIX_iOS/HOLIX_iOS/Global/Component/TopTabBar/TopTabCell.swift
  HOLIX_iOS/HOLIX_iOS/Global/Extension/NSObject+ClassName.swift
  HOLIX_iOS/HOLIX_iOS/Global/Extension/UIView.swift
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_alert_ios.imageset/ic_alert_ios.svg
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_alert_ios_active.imageset/ic_alert_ios.svg
  HOLIX_iOS/HOLIX_iOS/View/Base/MainTabBarController.swift
  HOLIX_iOS/HOLIX_iOS/View/Base/ViewController.swift
  HOLIX_iOS/HOLIX_iOS/View/Home/HomeViewController.swift
Labels: Feat, Setting, 정욱

#19 [setting] API 통신을 위한 기본 구조 구성
  .gitignore
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/NetWork/Core/APIService.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Core/Endpoint.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Core/HTTPMethod.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Core/NetworkError.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Request/.gitkeep
  HOLIX_iOS/HOLIX_iOS/NetWork/Response/StudyResponse.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Services/HomeService.swift
  HOLIX_iOS/HOLIX_iOS/Resource/Info.plist
  HOLIX_iOS/HOLIX_iOS/View/Home/Layout/HomeSectionLayoutFactory.swift
Labels: Feat, Network, Setting, 정욱

#21 [feat] Chatting View 구현
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/Global/Component/CustomTextView.swift
  HOLIX_iOS/HOLIX_iOS/Global/Component/TagView.swift
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_add_circle_ios.imageset/Contents.json
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_add_circle_ios.imageset/ic_add_circle_ios-1.svg
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_add_circle_ios.imageset/ic_add_circle_ios-2.svg
  HOLIX_iOS/HOLIX_iOS/Resource/Assets.xcassets/Icon/ic_add_circle_ios.imageset/ic_add_circle_ios.svg
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingCell/BubbleLabelView.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingCell/ChattingCell.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingMockData.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingViewController.swift
Labels: Feat, 재현

#31 [Feat] MyClub API Connect
  HOLIX_iOS/HOLIX_iOS/Global/Extension/UIImageView.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Response/ClubResponse.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Services/ClubService.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/Cell/MyClubCell.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/View/MyClubView.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/ViewController/MyClubMainViewController.swift
Labels: Feat, Network, 소은

#30 [Feat] Chatting API Connect
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HOLIX_iOS/HOLIX_iOS/Global/Component/NoticeButton.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Response/ClubChattingResponse.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Response/ClubDetailResponse.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Services/ClubChattingService.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingCell/ChattingCell.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingViewController.swift
  HOLIX_iOS/HOLIX_iOS/View/ClubDetail/ClubDetailViewController.swift
  HOLIX_iOS/HOLIX_iOS/View/ClubDetail/ClubInfoView.swift
Labels: Feat, Network, 재현

#33 [Chore] MyClub 관련 여러 수정사항
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/Model/RecommendedClubModel.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/Cell/MyClubCell.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/Cell/RecommendedClubCell.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/View/MyClubView.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/ViewController/MyClubMainViewController.swift
Labels: Chore, Feat, 소은

#36 [Feat] MyClub, ClubDetailView 연결
  HOLIX_iOS/HOLIX_iOS.xcodeproj/project.pbxproj
  HOLIX_iOS/HOLIX_iOS/Global/Component/CategoryTabBar/CategoryTabBarView.swift
  HOLIX_iOS/HOLIX_iOS/Global/Component/CustomNavigationBar.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Response/ClubChattingResponse.swift
  HOLIX_iOS/HOLIX_iOS/NetWork/Services/ClubChattingService.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingCell/ChattingCell.swift
  HOLIX_iOS/HOLIX_iOS/View/Chatting/ChattingViewController.swift
  HOLIX_iOS/HOLIX_iOS/View/ClubDetail/ClubDetailViewController.swift
  HOLIX_iOS/HOLIX_iOS/View/ClubDetail/ClubInfoView.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/View/MyClubView.swift
  HOLIX_iOS/HOLIX_iOS/View/MyClub/ViewController/MyClubMainViewController.swift
Labels: Feat, 소은
